sudo: no
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.6"

before_install:
  - pip install --no-deps -r requirements.txt

script:
  - python setup.py test

notifications:
  webhooks: http://leeroybot.lonnen.com/hubot/travis?room=%23breakpad
